// firedamp on cartograph — everything firedamp-specific is this config plus
// two hook modules: attribution.js (static attribution + wind) and
// candidates.js (ch4id feature catalogue from features.fgb).

import { mount } from './vendor/cartograph/app.js';
import { map as dd } from './vendor/dd/palette.js';
import { escapeHtml } from './vendor/cartograph/util.js';
import { loadAttributions, enrich } from './attribution.js';
import { addCandidateLayers, clearSelection } from './candidates.js';
import { clearProbabilityOverlay, initProbabilityOverlay, showProbabilityOverlay } from './overlay.js';

// plumes live in the central datadesk store; localhost and the private deploy
// (dist.sh local mode, whose baked parquet carries ghgsat) read the local copy.
// hourly cache-buster: the store key is stable and refreshed ~6-hourly.
const bucket = document.querySelector('meta[name="data-bucket"]')?.content;
const PLUMES = location.hostname === 'localhost' || document.querySelector('meta[name="local-plumes"]')
    ? 'data/plumes.parquet' : `${bucket}/views/plumes/data.parquet?v=${Math.floor(Date.now() / 36e5)}`;
// attributions live on the store too (ch4id `sync push` exports the contract)
const ATTRIBUTIONS = `${bucket}/views/attributions/data.parquet?v=${Math.floor(Date.now() / 36e5)}`;

const SRCS = ['cm', 'imeo', 'sron', 'ghgsat', 'dd'];
const PRIVATE = new Set(['ghgsat']);   // only ever in the private deploy's baked parquet
const COLOR = { cm: dd.adjusted.cyan, imeo: dd.adjusted.magenta, sron: dd.adjusted.yellow, ghgsat: dd.adjusted.orange, dd: dd.adjusted.green };
const LABEL = { cm: 'Carbon Mapper', imeo: 'IMEO / MARS', sron: 'SRON', ghgsat: 'GHGSat', dd: 'Data Desk' };
const SECTOR = { og: 'Oil & Gas', coal: 'Coal', waste: 'Waste', other: 'Other' };

// dd flare marking, one size for every plume (rate lives in the key filter
// and the data table); grows gently with zoom, the burnoff ramp
const ICON = ['interpolate', ['linear'], ['zoom'], 2, 0.55, 10, 0.8, 14, 1];

// null when the provider published no rate estimate
const rateT = p => p.rate == null ? null : (Number(p.rate) / 1000).toFixed(1);

function sourceUrl(p) {
    if (!p.id) return null;
    if (p.src === 'cm') return `https://data.carbonmapper.org/?plume_id=${encodeURIComponent(p.id)}`;
    if (p.src === 'sron' && p.link) return `https://ftp.sron.nl/pub/memo/CSVs/${encodeURIComponent(p.link)}`;
    if (p.src === 'dd') {
        if (p.link) return /^https?:/.test(p.link) ? p.link : `${bucket}/${p.link.replace(/^\//, '')}?v=viridis`;
        // Compatibility with the pre-canonical ch4id catalogue.
        const [, site, scene] = p.id.split(':');
        if (scene) return `${bucket}/${scene.startsWith('EMIT') ? 'hypergas' : 'mars-s2l'}/plumes/${site}_${scene}.png`;
    }
    return null;
}

function overlayUrl(p) {
    if (p.src !== 'dd' || !p.overlay) return null;
    return /^https?:/.test(p.overlay) ? p.overlay : `${bucket}/${p.overlay.replace(/^\//, '')}?v=viridis`;
}

mount({
    title: 'Firedamp',
    badge: 'beta',
    subtitle: 'Methane plume aggregator',
    about: `<p>Firedamp aggregates satellite methane plume detections from
        <a href="https://carbonmapper.org" target="_blank" rel="noopener">Carbon Mapper</a>,
        UNEP's <a href="https://methanedata.unep.org" target="_blank" rel="noopener">International Methane Emissions Observatory</a>
        and <a href="https://earth.sron.nl/methane-emissions/" target="_blank" rel="noopener">SRON</a>,
        hosted by <a href="https://datadesk.eco" target="_blank" rel="noopener">Data Desk</a>.</p>
        <p>Recent plumes carry provisional attributions generated by the <a href="https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro" target="_blank" rel="noopener">DeepSeek V4 Pro</a> model.
        We run DeepSeek in a version of the <a href="https://pi.dev/" target="_blank" rel="noopener">pi</a>
        coding harness with access to a database of 15 million candidate sources from
        <a href="https://globalenergymonitor.org" target="_blank" rel="noopener">Global Energy Monitor</a>,
        <a href="https://www.edf.org" target="_blank" rel="noopener">EDF OGIM</a>,
        <a href="https://www.openstreetmap.org" target="_blank" rel="noopener">OpenStreetMap</a> and
        <a href="https://mapstand.com" target="_blank" rel="noopener">MapStand</a>, as well as original raster data
        and geospatial analysis tools.</p>
        <p>This functionality is an experiment, and while results for high-resolution sensors such as Tanager-1
        are promising, attributions are more speculative for lower-resolution sensors like TROPOMI. Your feedback
        will help inform our work: <a href="mailto:hello@datadesk.eco">hello@datadesk.eco</a></p>`,
    search: true,
    map: { center: [-98, 39], zoom: 4, minZoom: 1.5, maxZoom: 18 },
    data: {
        files: { plumes: PLUMES, attributions: ATTRIBUTIONS },
        prefetch: ['plumes'],
    },

    sources: async ({ read, fc }) => {
        const [plumes, attribs] = await Promise.all([
            read('plumes'),
            loadAttributions(),
        ]);
        for (const p of plumes) if (attribs.has(p.id)) p.attr = 1;
        // clusters only when far out — points take over from z5 (~UK-sized viewport)
        return { plumes: { data: fc(plumes), cluster: true, clusterMaxZoom: 4, clusterRadius: 30,
                           clusterProperties: { rate_sum: ['+', ['coalesce', ['get', 'rate'], 0]] } } };
    },

    layers: [
        ...SRCS.map(src => ({
            id: `plumes-${src}`, type: 'symbol', source: 'plumes',
            filter: ['all', ['!', ['has', 'point_count']], ['==', ['get', 'src'], src]],
            hover: p => `<span class="dd-title">${rateT(p) ? `${rateT(p)} t/hr` : 'rate n/a'}</span><br>${LABEL[p.src]}${p.dt ? ' · ' + p.dt : ''}`,
            layout: {
                'icon-image': `flare-${COLOR[src]}`,
                'icon-size': ICON,
                'icon-allow-overlap': true,
                'icon-ignore-placement': true,
                // t/hr up-and-right (dd label rule); colliding labels drop, icons
                // stay; rate-less plumes get no label
                'text-field': ['case', ['==', ['typeof', ['get', 'rate']], 'number'], ['concat',
                    ['number-format', ['/', ['get', 'rate'], 1000], { 'max-fraction-digits': 1 }], ' t/hr'], ''],
                'text-font': ['Montserrat Regular'], 'text-size': 10,
                'text-anchor': 'bottom-left', 'text-offset': [0.7, -0.7],
                'text-optional': true,
            },
            paint: { 'text-color': dd.adjusted.white },
        })),
        {
            // white default-state flare with total t/hr up-and-right (dd label rule)
            id: 'plumes-clusters', type: 'symbol', source: 'plumes',
            filter: ['has', 'point_count'],
            layout: {
                'icon-image': `flare-${dd.adjusted.white}`,
                'icon-size': ICON,
                'icon-allow-overlap': true, 'icon-ignore-placement': true,
                // round before formatting: maplibre drops a 0 'max-fraction-digits'
                'text-field': ['concat',
                    ['number-format', ['round', ['/', ['get', 'rate_sum'], 1000]], {}], ' t/hr'],
                'text-font': ['Montserrat Regular'], 'text-size': 10,
                'text-anchor': 'bottom-left', 'text-offset': [0.7, -0.7],
                'text-allow-overlap': true,
            },
            paint: { 'text-color': dd.adjusted.white },
        },
    ],

    filters: [
        {
            key: 'attr', label: 'Attribution', value: 'all',
            options: [{ value: 'all', label: 'All' }, { value: 'yes', label: 'Attributed' }],
            pred: v => v === 'yes' ? p => p.attr === 1 : null,
        },
        {
            key: 'date', label: 'Date', value: 'all',
            options: [{ value: 'all', label: 'All' }, { value: '2025', label: "'25" },
                      { value: '2026', label: "'26" }, { value: '60d', label: '-60d' }],
            pred: v => v === 'all' ? null
                : v === '60d' ? (cut => p => p.dt >= cut)(new Date(Date.now() - 60 * 864e5).toISOString().slice(0, 10))
                : p => (p.dt || '').startsWith(v),
        },
    ],

    key: ctx => [
        {
            // toggleable rate ranges: active rows OR into the data filter
            label: 'Rate (t/hr)',
            rows: [['10+', 10], ['5–10', 5, 10], ['1–5', 1, 5], ['< 1', 0, 1], ['n/a']].map(([label, lo, hi]) => ({
                swatch: { mark: 'flare', color: dd.adjusted.white }, label,
                pred: lo == null ? p => p.rate == null
                    : p => p.rate != null && p.rate >= lo * 1000 && (!hi || p.rate < hi * 1000),
            })),
        },
        {
            // source rows filter the data too, so clusters re-form without them
            label: 'Source',
            rows: SRCS.filter(src => !PRIVATE.has(src) || ctx.sources.plumes.features.some(f => f.properties.src === src))
                .map(src => ({ swatch: { mark: 'flare', color: COLOR[src] }, label: LABEL[src], pred: p => p.src === src })),
        },
    ],

    table: [
        {
            label: 'Detections',
            rows: ({ sources }) => sources.plumes.features.map(f => f.properties),
            cols: ['id', 'src', 'dt', 'rate', 'sat', 'sec', 'lat', 'lon'],
        },
        {
            // rows aren't plume properties, so the legend preds don't apply
            label: 'Attributions', filter: false,
            rows: async ({ read }) => (await read('attributions',
                { columns: ['id', 'source_label', 'source_kind', 'operator', 'confidence', 'lat', 'lon'] }))
                .sort((a, b) => String(a.source_label).localeCompare(String(b.source_label))),
            cols: ['id', 'source_label', 'source_kind', 'operator', 'confidence', 'lat', 'lon'],
        },
    ],

    detail: {
        layers: SRCS.map(src => `plumes-${src}`),
        hashKey: 'plume', flyZoom: 15,
        title: p => ({ text: p.id || '—', href: sourceUrl(p) }),
        html: p => `
            <div class="fd-badges">
                <span style="color:${COLOR[p.src]}">${LABEL[p.src] || escapeHtml(p.src)}</span>
                ${p.sec ? `<span class="dd-secondary">${SECTOR[p.sec] || escapeHtml(p.sec)}</span>` : ''}
            </div>
            <div class="fd-stats">
                <div><div class="fd-stat-big">${rateT(p) ?? '—'}</div><div class="dd-secondary">t/hr${p.unc ? ` ±${(p.unc / 1000).toFixed(1)}` : ''}</div></div>
                <div id="stat-wind"><div class="fd-stat-big">…</div><div class="dd-secondary">wind</div></div>
                <div><div class="fd-stat-big">${escapeHtml(p.sat || '—')}</div><div class="dd-secondary">satellite</div></div>
                <div><div class="fd-stat-big">${escapeHtml(p.dt || '—')}</div><div class="dd-secondary">date</div></div>
            </div>
            <div class="fd-analysis">
                <div class="dd-secondary">Analysis</div>
                <div id="analysis" class="dd-secondary">Loading…</div>
            </div>`,
        onShow: p => { enrich(p); showProbabilityOverlay(p, overlayUrl(p)); },
        onClose: () => { clearSelection(); clearProbabilityOverlay(); },
    },

    ready: ({ map }) => { initProbabilityOverlay(map); addCandidateLayers(map); },
});
